apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: statuspagemonitors.statuspage.atheniaai.com
spec:
  group: statuspage.athenaiai.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resourceType:
                  type: string
                  enum: [Pod, Service, Ingress]
                resourceName:
                  type: string
                namespace:
                  type: string
              required: [resourceType, resourceName, namespace]
  scope: Namespaced
  names:
    plural: statuspagemonitors
    singular: statuspagemonitor
    kind: StatusPageMonitor
    shortNames:
      - spm