---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statuspage-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statuspage-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["statuspage.example.com"]
  resources: ["statuspagemonitors"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: statuspage-operator
subjects:
- kind: ServiceAccount
  name: statuspage-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: statuspage-operator
  apiGroup: rbac.authorization.k8s.io